### ISSUE TITLE
Add support for Yoast Video SEO extention

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods-seo#11]
https://yoast.com/wordpress/plugins/video-seo/
https://kb.yoast.com/kb/video-seo-plugin-configuration-guide/
https://kb.yoast.com/kb/how-does-the-plugin-work-with-videos-in-custom-fields/#create
- [ ] XML sitemaps
- [ ] Content analysis?? (don't think they use videos for content analysis though..)

**Comment by sc0ttkclark** [comment]
Good idea! Any other Yoast stuff we can integrate with?

**Comment by JoryHogeveen** [comment]
I'm checking all extensions.
What I found is that most are "standalone". When the address field is ready we could check if there are posibilities to integrate with Local SEO.

The Video SEO module already allows custom fields though we'll have to check how this works. From what I read it requires are valid oEmbed url.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Can't find any integrations left at this moment.
The Video SEO module already allows custom fields so no work for Pods here.

The Local SEO module could be integrated with the new address field in 2.7. But lets do that in a next version.

2.1 is a go I'd say!
