### ISSUE TITLE
Can't get to work with latest Yoast SEO

### ISSUE THREAD

**Issue by mastef** [pods-framework/pods-seo#14]
Yoast SEO removed the sitemaps xml configuration page, so it might not be possible to configure Pods SEO right now?

**Comment by sc0ttkclark** [comment]
This plugin is one we need to look at with the latest Yoast SEO and WP 5.0 releases.

**Comment by mastef** [comment]
For anyone else looking for this - I've gotten around it temporarily by creating [pods sitemaps programmatically in yoast seo](https://blog.stefanxo.com/2018/12/how-to-add-a-sitemap-of-your-pod-page-to-wordpress-yoast-seo/).

**Comment by sc0ttkclark** [comment]
This plugin/repo are no longer supported and are being archived. I wish we had more funding to keep this going, I'm sorry.
